/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JS config input (OpenClaw-compatible field names). */
export interface FeishuConfigInput {
  appId: string
  appSecret: string
  domain?: string
  connectionMode?: string
  allowedUsers?: Array<string>
  dmPolicy?: string
  groupPolicy?: string
  allowFrom?: Array<string>
  groupAllowFrom?: Array<string>
  groupRequireMention?: boolean
  encryptKey?: string
  verificationToken?: string
  webhookPort?: number
}
/** Create a Feishu channel from config. */
export declare function createChannelJs(config: FeishuConfigInput): FeishuChannelJs
/** Health check (standalone, for testing). */
export declare function healthCheckStandalone(): boolean
/** Feishu channel wrapper for Node.js. */
export declare class FeishuChannelJs {
  /** Send a text message to a chat. */
  send(message: string, recipient: string): Promise<void>
  /** Run health check. */
  healthCheck(): Promise<boolean>
  /**
   * Start listening; invokes `on_message` for each received message (JSON string).
   *
   * Connection lifecycle signals are sent as special JSON messages:
   *   - `{"__signal__":"connected"}` when WebSocket connects
   *   - `{"__signal__":"disconnected","error":"..."}` on disconnect/error
   *   - `{"__signal__":"error","error":"..."}` on fatal error
   *
   * Returns when the listener has started. Listening runs in background.
   */
  listen(onMessage: (...args: any[]) => any): void
}
